services:
  database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - buki-database:/var/lib/mysql
    ports:
      - "3306:3306"
  api-dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/buki-app/
    network_mode: service:database
    command: sleep infinity
    user: root
    depends_on:
      - database

volumes:
  buki-database:
    driver: local
